-- CADASTRAR ALUNO
-- INSERT INTO ALUNO VALUES (ID, NOME, EMAIL, CURSO, DATA_NASCIMENTO, ENDERECO);
-- CADASTRAR TURMA
-- INSERT INTO TURMA VALUES (ID, SALA, HORARIO);
-- CADASTRAR ALUNO EM DISCIPLINA
-- INSERT INTO MATRICULA VALUES (ALUNO_ID, MATRICULA_ID);
-- CADASTRAR PROFESSOR
-- INSERT INTO PROFESSOR VALUES (ID, NOME, DEPARTAMENTO, EMAIL, DATA_NASCIMENTO);
-- CADASTRAR DISCIPLINA
-- INSERT INTO DISCIPLINA VALUES (ID, NOME, CARGA_HORARIA);
-- CADASTRAR PROFESSOR EM DISCIPLINA
-- INSERT INTO LECIONA VALUES (PROFESSOR_ID, DISCIPLINA_ID, TURMA_ID);

-- MOSTRAR DADOS ALUNO
SELECT * FROM ALUNO;

-- MOSTRAR DADOS TURMA
SELECT * FROM TURMA;

-- MOSTRAR DADOS PROFESSOR
SELECT * FROM PROFESSOR;

-- MOSTRAR DADOS DISCIPLINA
SELECT * FROM DISCIPLINA;

-- MOSTRAR DISCIPLINAS DE UM ALUNO
SELECT
    A.NOME AS ALUNO,
    D.NOME   AS DISCIPLINA
FROM
         ALUNO A
    JOIN MATRICULA M ON A.ID = M.ALUNO_ID
    JOIN DISCIPLINA D ON M.DISCIPLINA_ID = D.ID
WHERE
    A.ID = 1;

-- MOSTRAR TURMAS DE UM PROFESSOR
SELECT
    P.NOME AS PROFESSOR,
    T.ID   AS TURMA
FROM
    PROFESSOR P
    JOIN LECIONA L ON P.ID = L.PROFESSOR_ID
    JOIN TURMA   T ON L.TURMA_ID = T.ID
WHERE
    P.ID = 1;

-- MOSTRAR DISCIPLINAS LECIONADAS POR UM PROFESSOR
SELECT
    P.NOME AS PROFESSOR,
    D.NOME AS DISCIPLINA
FROM
         PROFESSOR P
    JOIN LECIONA    L ON P.ID = L.PROFESSOR_ID
    JOIN DISCIPLINA D ON L.DISCIPLINA_ID = D.ID
WHERE
    P.ID = 1;

-- Consulta Interna
SELECT
    A.NOME AS ALUNO_NOME,
    D.NOME AS DISCIPLINA_NOME,
    T.SALA,
    T.HORARIO
FROM
         MATRICULA M
    INNER JOIN ALUNO      A ON M.ALUNO_ID = A.ID
    INNER JOIN TURMA      T ON M.TURMA_ID = T.ID
    INNER JOIN LECIONA    L ON T.ID = L.TURMA_ID
    INNER JOIN DISCIPLINA D ON L.DISCIPLINA_ID = D.ID;

-- Consulta Externa
SELECT
    A.NOME AS ALUNO_NOME,
    M.ALUNO_ID,
    M.TURMA_ID
FROM
    ALUNO     A
    LEFT JOIN MATRICULA M ON A.ID = M.ALUNO_ID;

-- Sentença de grupo envolvendo as junções dos anteriores;
SELECT
    D.NOME   AS DISCIPLINA_NOME,
    COUNT(*) AS TOTAL_ALUNOS_MATRICULADOS
FROM
    DISCIPLINA D
    LEFT JOIN LECIONA    L ON D.ID = L.DISCIPLINA_ID
    LEFT JOIN TURMA      T ON L.TURMA_ID = T.ID
    LEFT JOIN MATRICULA  M ON T.ID = M.TURMA_ID
GROUP BY
    D.NOME;

-- Sentença com a cláusula HAVING a partir da consulta do item e, anterior
SELECT
    D.NOME   AS DISCIPLINA_NOME,
    COUNT(*) AS TOTAL_ALUNOS_MATRICULADOS
FROM
    DISCIPLINA D
    LEFT JOIN LECIONA    L ON D.ID = L.DISCIPLINA_ID
    LEFT JOIN TURMA      T ON L.TURMA_ID = T.ID
    LEFT JOIN MATRICULA  M ON T.ID = M.TURMA_ID
GROUP BY
    D.NOME
HAVING
    COUNT(*) >= 3;

-- Sentença envolvendo subconsulta a partir das consultas geradas nos itens anteriores.
SELECT A.NOME AS ALUNO_NOME
FROM ALUNO A
WHERE A.ID IN (
  SELECT M.ALUNO_ID
  FROM MATRICULA M
  JOIN TURMA T ON M.TURMA_ID = T.ID
  JOIN LECIONA L ON T.ID = L.TURMA_ID
  WHERE L.PROFESSOR_ID = 1
);
